name: Deploy to TestPyPi

on:
  push:
    branches:
    - '**'        # run for all branches
    branches-ignore:
    - 'master'    # except master

jobs:
    build-n-publish-testing:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Build and publish to pypi
            continue-on-error: true
            uses: JRubics/poetry-publish@v1.6
            with:
                python_version: '3.7.1'
                poetry_version: '==1.1.7'  # (PIP version specifier syntax)
                pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
                repository_name: 'testpypi'
                repository_url: 'https://test.pypi.org/legacy/'

