name: Deploy to PyPi

on:
  push:
    tags:
      - "v*.*.*"

jobs:
    build-n-publish:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Build and publish to pypi
            uses: JRubics/poetry-publish@v1.6
            with:
                python_version: '3.7.1'
                poetry_version: '==1.1.7'  # (PIP version specifier syntax)
                pypi_token: ${{ secrets.PYPI_TOKEN }}
